application: zoecarebzn
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /api/(.*)
  script: api
- url: /.*
  static_files: static/html/main.html
  upload: /
