application: zoecarebzn
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /api/.*
  script: server/api
- url: /static
  static_dir: client/static
- url: /.*
  static_files: client/static/index.html
  upload: /

skip_files:
- ^(.*/)?README\.md$
- ^(.*/)?\..*$
- ^(.*/)?bower\.json$
- ^(.*/)?gulpfile\.js$
- ^(.*/)?node_modules$
- ^(.*/)?package\.json$
# bower_components
# find client/static/bower_components -type f -name '*.*' | grep -v -e '^.*\.git' | rev | cut -f 1 -d '.' | rev | sort -u
- ^(.*/)?.*\.editorconfig$
- ^(.*/)?.*\.gzip$
- ^(.*/)?.*\.jshintignore$
- ^(.*/)?.*\.jshintrc$
- ^(.*/)?.*\.less$
- ^(.*/)?.*\.txt$
- ^(.*/)?.*\.xml$
- ^(.*/)?.*\.yml$
