application: zoecarebzn
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /api/.*
  script: server/api
- url: /static
  static_dir: client/static
- url: /.*
  static_files: client/static/index.html
  upload: /

skip_files:
- ^(.*/)?gulpfile\.js$
- ^(.*/)?README\.md$
- ^(.*/)?\..*$
- ^(.*/)?bower\.json$
- ^(.*/)?node_modules$
- ^(.*/)?package\.json$
