application: zoecarebzn
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /api/(.*)
  script: api/api
- url: /static
  static_dir: static
- url: /.*
  static_files: static/index.html
  upload: /

skip_files:
- ^(.*/)?Gruntfile\.js$
- ^(.*/)?README\.md$
- ^(.*/)?\..*$
- ^(.*/)?archive$
- ^(.*/)?bower\.json$
- ^(.*/)?package\.json$

